version: "3.9"

services:
  frontend:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host --port 5174"
    ports:
      - "5174:5174"
    volumes:
      - ./:/app
    environment:
      - HOST=0.0.0.0
      - PORT=5174
    depends_on:
      - api

  api:
    image: node:18-alpine
    working_dir: /app/api
    command: sh -c "npm install && node --watch server.js"
    env_file:
      - ./api/.env
    ports:
      - "3005:3005"
      - "8080:8080"
    volumes:
      - ./:/app
    restart: unless-stopped
