apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-book-site-api
  labels:
    app: chat-book-site-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-book-site-api

  template:
    metadata:
      labels:
        app: chat-book-site-api

    spec:
      containers:
        - name: chat-book-site-api
          image: elijahred23/chat-book-site-api:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8080   # The ONLY port you need

          envFrom:
            - secretRef:
                name: chat-book-site-api-secret
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/tts-sa/tts-sa.json
          volumeMounts:
            - name: tts-sa
              mountPath: /var/secrets/tts-sa
              readOnly: true
      volumes:
        - name: tts-sa
          secret:
            secretName: tts-sa
---
apiVersion: v1
kind: Service
metadata:
  name: chat-book-site-api
spec:
  type: LoadBalancer
  selector:
    app: chat-book-site-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
